### ISSUE TITLE
✅ | Publish RFP for future work

### ISSUE THREAD

**Issue by jsoares** [protocol/ConsensusLab#100]
## Description
Publish an RFP for funding future work on Pikachu.

**Comment by sa8** [comment]
[Here](https://hackmd.io/@consensuslab/H1cK_eKv9) is the link to the draft. I have added numbers as we discussed on Friday.

**Comment by jsoares** [comment]
https://github.com/protocol/research-grants/blob/master/RFPs/rfp-012-checkpointing-fil-into-btc.md
