### ISSUE TITLE
Atomic primitives and sample actor with support for atomic execution

### ISSUE THREAD

**Issue by jsoares** [protocol/ConsensusLab#125]
**For work tracking purposes.**

Refer to the parent project issue for high-level discussion and resources.

**Comment by jsoares** [comment]
- Deliverable: SCA with atomic execution implemented and a sample user-defined contract using locking primitives.
    - Dependency: SCA in Rust. Already fulfilled
    - Date: 10th September
    - Demo: September demo-day. Implementation of an atomic-execution contract.

**Comment by jsoares** [comment]
Supersedes #96

**Comment by adlrocha** [comment]
[PR](https://github.com/adlrocha/builtin-actors/pull/17) with an improved implementation of the protocol. It is close to be done but not yet as the focus was a bit de-railed towards BuilderNet and Y4. Let's leave it open until this PR is merged.
