### ISSUE TITLE
🎯 | B3.1-M2: Rebase Lotus with FVM integration

### ISSUE THREAD

**Issue by jsoares** [protocol/ConsensusLab#126]
**For work tracking purposes.**

Refer to the parent project issue for high-level discussion and resources.

**Comment by jsoares** [comment]
- Deliverable: The main branch of Eudico (or a fork with FVM-M2 support) implements HC with FVM.
    - Dependency: ideally, FVM-M2 in lotus master (if this doesn't happen in time, we'll have to keep our own branch).
    - Date: 15th October
    - Demo: October demo-day. End-to-end lifecycle of a subnet integrated with FVM

**Comment by adlrocha** [comment]
Superseded by https://github.com/protocol/ConsensusLab/issues/185
