### ISSUE TITLE
🎯 | B3.2-M1: Consensus interface and dummy consensus in Forest

### ISSUE THREAD

**Issue by jsoares** [protocol/ConsensusLab#127]
**For work tracking purposes.**

Refer to the parent project issue for high-level discussion and resources.

**Comment by jsoares** [comment]
- Deliverable: 
        - __Does Forest need FVM integration?__ To call the FVM actors, it sounds like it does. The main branch has its own VM, similar but not the same as the FVM code I have seen. Is the upgrade to use FVM already happening, perhaps?
        - __Abstract Consensus Interface__: Make consensus pluggable. We want to be able to run Forest with _Delegated Consensus_, meaning the same validator produces all the blocks. This is to showcase that we can, and that subnets can choose their own consensus. 
        - __Delegated Consensus__: Needs to be implemented once the code supports choosing.
        - __Documentation__: The Forest team has no documentation about how consensus works, and the people who worked on it have already moved on, so it might be a good idea to prepare some documentation, to help them with reviews at least.
        - __Reviews__: We can ask the Forest team to review and potentially merge the code at this stage as it should be just refactoring.
        - __Testing__: Can we hook into an existing testbed to make sure we haven't broken anything?
    - Date: 15th August
    - Demo: 1 September

**Comment by aakoshh** [comment]
https://github.com/ChainSafe/forest/pull/1656

**Comment by aakoshh** [comment]
[Forest PR](https://github.com/ChainSafe/forest/pull/1680) to factor out the weight function into Consensus

**Comment by aakoshh** [comment]
[Started working](https://github.com/aakoshh/forest/pull/2/files) on Delegated Consensus

**Comment by jsoares** [comment]
We've decided to end this work early following M1 and put later milestones on hold. I'll close subsequent issues appropriately.
