### ISSUE TITLE
🥽 | Yellow: General Consensus Layer

### ISSUE THREAD

**Issue by jsoares** [protocol/ConsensusLab#2]
@jsoares commented on [Tue Nov 30 2021](https://github.com/protocol/ConsensusLab-private/issues/46)

## Description
The goal of the yellow work area of projects is to design and implement efficient consensus (total order) BFT and Proof of Stake (PoS) protocols targeting different deployment scenarios. Notably, different consensus protocols might be applied in the context of thousands of nodes as opposed to up to low hundred or so of nodes. Additionally, mechanisms for fairness (front running prevention) need to be in place. The work in this layer additionally explores consensus and blockchain constructions with semantics weaker than total order. 

## Scope
* MUST prevent front running 
    * MAY use time-lock/encrypted transactions 
* MUST have production-ready implementation(s) of BFT/PoS consensus
    * SHOULD have very efficient BFT/PoS protocol for scales up to low hundred nodes
    * SHOULD have reasonably efficient BFT/PoS protocol for scales of low thousands of nodes
    * MAY consider alternative trust models (e.g., Stellar, Asymmetric Quorums)
* MUST provide datacenter level performance in case consensus nodes are geographically co-located
* SHOULD explore semantics weaker than total order (e.g., causal order)
* MUST produce proofs of correctness
    * SHOULD automatically verify or model-check designs 

## Projects
* #8 
* #13
* #9 
* #10 
* #14

**Comment by dnkolegov** [comment]
@jsoares In which project time-lock/encrypted transactions are addressed?

**Comment by jsoares** [comment]
@dnkolegov At this point, we don't have a specific CL project around timelock encryption -- this will likely come up in Y4 but it can also be a concern subnet consensus (or not, use-case dependent). Related work on enabling timelock encryption is being done by the drand team and external partners. See [blog post](https://drand.love/blog/2022/02/21/multi-frequency-support-and-timelock-encryption-capabilities/#unchained-randomness-timed-encryption).
