### ISSUE TITLE
Write "How to Add a New Consensus Protocol into Eudico" doc

### ISSUE THREAD

**Issue by jsoares** [protocol/ConsensusLab#38]
@jsoares commented on [Thu Jan 27 2022](https://github.com/protocol/ConsensusLab-private/issues/69)

Create a “How to Add a New Consensus Protocol into Eudico” document based on the implementations of the PoW, delegated consensus, and Tendermint (if approved) in the Eudico codebase

**Comment by dnkolegov** [comment]
https://github.com/filecoin-project/eudico/blob/tendermint-exp/chain/consensus/tendermint/README.md
