### ISSUE TITLE
Prepare M2 demo materials

### ISSUE THREAD

**Issue by jsoares** [protocol/ConsensusLab#41]
@jsoares commented on [Thu Jan 27 2022](https://github.com/protocol/ConsensusLab-private/issues/65)

**Comment by dnkolegov** [comment]
Video - https://drive.google.com/file/d/1AILi4wQK1ZT07vFMYiUxdtGG63NbANwJ/view?usp=sharing
Slides - https://drive.google.com/file/d/1AILi4wQK1ZT07vFMYiUxdtGG63NbANwJ/view?usp=sharing
