### ISSUE TITLE
Perform sanity tests with 4 nodes

### ISSUE THREAD

**Issue by jsoares** [protocol/ConsensusLab#42]
@jsoares commented on [Thu Jan 27 2022](https://github.com/protocol/ConsensusLab-private/issues/64)

**Comment by dnkolegov** [comment]
Tests are implemented in https://github.com/filecoin-project/eudico/blob/61fc74cf2718a4e09f910e646886161ca13084db/itests/eudico_consensus_test.go#L24.

The deployment consists of a Tendermint cluster with 4 nodes - https://github.com/filecoin-project/eudico/blob/61fc74cf2718a4e09f910e646886161ca13084db/Makefile#L112
