### ISSUE TITLE
Benchmarking the implementation

### ISSUE THREAD

**Issue by jsoares** [protocol/ConsensusLab#54]
@dnkolegov commented on [Wed Feb 23 2022](https://github.com/protocol/ConsensusLab-private/issues/87)

---

@jsoares commented on [Fri Feb 25 2022](https://github.com/protocol/ConsensusLab-private/issues/87#issuecomment-1050787053)

@dnkolegov I'll transfer this to the public repo; best to create there directly whenever possible 🙏

**Comment by dnkolegov** [comment]
Benchmark function has been implemented and can be used with all supported consensus - https://github.com/filecoin-project/eudico/blob/ab1b2afe0667e876b41252535e4ef9a47f7417e5/chain/consensus/benchmark/benchmark.go#L12
