### ISSUE TITLE
🎯 | Y3-M3: Practical consensus protocol (MVP)

### ISSUE THREAD

**Issue by jsoares** [protocol/ConsensusLab#63]
## Description

Refer to the [parent project](https://github.com/protocol/ConsensusLab/issues/9) issue for high-level discussion and resources.

This milestone targets an MVP for subnet consensus in the [Eudico](https://github.com/filecoin-project/eudico) Filecoin client. At this milestone, the [Mir](https://github.com/filecoin-project/mir) implementation will comprise all features that are essential for it to operate as a subnet consensus protocol and will be available for selection as one when deploying Eudico.

The high-level concepts that behind the implementation are described in the design document: [Implementation of Eudico’s Ordering Layer](https://hackmd.io/P59lk4hnSBKN5ki5OblSFg)

### Items to address (Priority 0)

- https://github.com/filecoin-project/mir/issues/74, 2 person-weeks, @matejpavlovic 
- https://github.com/filecoin-project/mir/issues/78, 3 person-weeks, @matejpavlovic 
- https://github.com/filecoin-project/mir/issues/81, 2 person-weeks
- https://github.com/filecoin-project/mir/issues/75, 3 person-weeks
- https://github.com/filecoin-project/mir/issues/80, 3 person-weeks, @sergefdrv (partly) 
- https://github.com/filecoin-project/mir/issues/77, 8 person-weeks
- https://github.com/filecoin-project/mir/issues/79, 3 person-weeks, @xosmig 
- https://github.com/filecoin-project/mir/issues/76, 5 person-weeks

Total estimate: 34 weeks

**Comment by matejpavlovic** [comment]
## 2022-08-15

### 📣 Updates
- @dnkolegov:
    - I am still working on Mir [reconfiguration](https://github.com/filecoin-project/eudico/pull/234) in Eudico
        - wrote tests
        - fixed bugs in old tests
        - fixed docs
        - prepared a test/demo scenario
    - PR review - [1](https://github.com/filecoin-project/mir/pull/185), [2](https://github.com/filecoin-project/mir/pull/184), [3](https://github.com/filecoin-project/mir/pull/180)
- @xosmig:
    - Working on Narwhal impl in Go
    - [Improving](https://github.com/filecoin-project/mir/pull/188) Mir
    - [Experimenting](https://github.com/xosmig/mir/pull/2) with improving DSL modules
- @matejpavlovic
    - [Mir now supports reconfiguration](https://github.com/filecoin-project/mir/pull/180). Node joining is tested with the chat app. Good candidate for the next Demo Day. Not secure yet due to partly stubby certificate verification code.
    - [Separate availability (mempool, content dissemination) layer integration with ISS](https://github.com/filecoin-project/mir/pull/183)
    
### 🧵 Discussion 
- Summary of sync brainstorming between @matejpavlovic and @xosmig about Mir, Narwhal, and reconfiguration:
    - Narwhal implementation:
        - What persistent storage system to use? BadgerDB was used just as an example in the design document, because it happens to be used by the (inherited) WAL implementation. In principle, @matejpavlovic has no concrete preference for a particular data store. What potentially might be relevant is [go-datastore](https://github.com/ipfs/go-datastore).
            - [Rust implementation](https://github.com/facebookresearch/narwhal) uses [RocksDB](http://rocksdb.org/).
        - The implementation will rely on a reliable communication abstraction. As for now, the unreliable Net module can be temporarily used as a stub. @matejpavlovic to check out the updated [GitHub discussion on reliable message delivery](https://github.com/filecoin-project/mir/discussions/132).
    - Narwhal garbage collection:
        - The garbage collection in Narwhal "cuts off" some dependencies. It may become a problem when we will be adding deduplication and censorship resistence. It is not immediately clear whether it's actually necessary: maybe we could garbage-collect only ordered blocks and add "weak references" as in DagRider to make sure every block is eventually ordered? Let's look more closely at the DagRider and think more about it.
    - Narwhal reconfiguration:
        - Multiple instances of Narwhal will co-exist, using a similar instantiation and garbage collection mechanism as ISS. The ordering layer (ISS in our case) already drives the advancing of epochs and configurations and the creation of checkpoints. It will simply emit analogous events to the availability module, which will instantiate and garbage-collect Narwhal instances accordingly.
        - As the ordering layer (ISS) is pulling its input from the availability layer (Narwhal), the availability certificates need not carry explicit epoch information. The ordering layer will simply pull the certificate from the corresponding instance of Narwhal. 
    - Mir nested modules:
        - In order to be able to kill old instances of the availability layer module and create new ones during the reconfiguration, we need something like [dynamic modules](https://github.com/filecoin-project/mir/discussions/127). However, we don't have a clean design for dynamic modules yet. Instead, we settled on a simpler alternative, which can be implemented with a tiny modification to how Mir core processes module ids.
            - TODO(@xosmig): write down the design for submodules either in discussions or in an ADR.
            - TODO(@matejpavlovic): Introduce structured module identifiers to enable suport for nested modules

### 🎯 Up next
- @dnkolegov:
    - finish integration of Mir reconfiguration
    - start working in integration of Mir's availability layer into Eudico
- @xosmig:
    - A simple stubby Narwhal prototype.
- @matejpavlovic
    - Merge reconfiguration and availability layer support
    - Prepare chat reconfiguration demo
