### ISSUE TITLE
🎯 | B3-M1: Translate SCA and subnet actors into Rust/WASM actor

### ISSUE THREAD

**Issue by jsoares** [protocol/ConsensusLab#94]
**For work tracking purposes.**

Refer to the parent project issue for high-level discussion and resources.

**Comment by jsoares** [comment]
Done pending FVM changes

**Comment by adlrocha** [comment]
We can consider this done with the implementations in the following forks:
- builtin-actors: https://github.com/adlrocha/builtin-actors
- ref-fvm; https://github.com/adlrocha/ref-fvm
And the user-defined subnet-actor: https://github.com/adlrocha/hc-subnet-actor

There probably will be on-going changes as FVM moves to M2, but the bulk of the work is done.
